"""
platform/youtube_upload.py — YouTube Data API v3 uploader
Reusable across any bot project. Update CHANNEL_HASHTAGS per project.

First-time local auth (one-time only):
  python platform/youtube_upload.py --auth

Normal usage (called by runner):
  from platform.youtube_upload import upload_to_youtube
  upload_to_youtube(video_path, title, description)

Secrets required (GitHub / environment):
  YOUTUBE_CLIENT_SECRETS  — full JSON from Google Cloud Console
  YOUTUBE_TOKEN_PICKLE    — base64-encoded token.pickle

Local files (gitignored):
  client_secrets.json     — OAuth credentials (download from Google Cloud)
  token.pickle            — saved auth token (generated by --auth)
"""

import os
import base64
import pickle
import argparse

SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

# Paths — relative to repo root (not this file's location)
_ROOT               = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLIENT_SECRETS_FILE = os.path.join(_ROOT, "client_secrets.json")
TOKEN_FILE          = os.path.join(_ROOT, "token.pickle")

# ── UPDATE per project ─────────────────────────────────────────
CHANNEL_HASHTAGS = "#Shorts #BhagavadGita #GitaDaily #Spirituality #DailyWisdom #GitaShloka"
# ──────────────────────────────────────────────────────────────


def _load_credentials_from_env():
    """
    In GitHub Actions, credentials come from secrets as env vars.
    Writes them to disk so the Google SDK can read them normally.
    """
    client_secrets_json = os.environ.get("YOUTUBE_CLIENT_SECRETS")
    token_pickle_b64    = os.environ.get("YOUTUBE_TOKEN_PICKLE")

    if client_secrets_json and not os.path.exists(CLIENT_SECRETS_FILE):
        with open(CLIENT_SECRETS_FILE, "w") as f:
            f.write(client_secrets_json)
        print("  [✓] client_secrets.json written from env")

    if token_pickle_b64 and not os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, "wb") as f:
            f.write(base64.b64decode(token_pickle_b64))
        print("  [✓] token.pickle written from env")


def get_credentials():
    """Load saved credentials or run OAuth flow (local only)."""
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from google.auth.transport.requests import Request

    # In CI, write credentials from env vars first
    _load_credentials_from_env()

    creds = None
    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, "rb") as f:
            creds = pickle.load(f)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
            with open(TOKEN_FILE, "wb") as f:
                pickle.dump(creds, f)
            print("  [✓] Token refreshed")
        else:
            # This only works locally (opens browser)
            flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRETS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
            with open(TOKEN_FILE, "wb") as f:
                pickle.dump(creds, f)
            print("  [✓] Credentials saved to token.pickle")

    return creds


def upload_to_youtube(video_path, title, description, tags=None, category_id="22"):
    """
    Upload a video as a YouTube Short.

    Args:
      video_path   : path to .mp4 file
      title        : video title (auto-appended with #Shorts if missing)
      description  : video description / caption
      tags         : list of tag strings (optional)
      category_id  : YouTube category (22=People&Blogs, 25=News, 27=Education)
                     Default 22 works well for spiritual/lifestyle content.
    """
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload

    creds   = get_credentials()
    youtube = build("youtube", "v3", credentials=creds)

    # Ensure #Shorts is in title (required for YouTube Shorts algorithm)
    yt_title = title[:90]
    if "#Shorts" not in yt_title:
        yt_title = yt_title[:83] + " #Shorts"

    yt_description = f"{description}\n\n{CHANNEL_HASHTAGS}"

    default_tags = ["Shorts", "BhagavadGita", "GitaDaily", "Spirituality",
                    "DailyWisdom", "GitaShloka", "KrishnaQuotes", "HinduPhilosophy"]

    body = {
        "snippet": {
            "title":       yt_title,
            "description": yt_description,
            "tags":        tags or default_tags,
            "categoryId":  category_id,
        },
        "status": {
            "privacyStatus":           "public",
            "selfDeclaredMadeForKids": False,
        },
    }

    media = MediaFileUpload(video_path, mimetype="video/mp4",
                            resumable=True, chunksize=1024 * 1024)

    print(f"  Uploading to YouTube: {yt_title}")
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"  Upload progress: {int(status.progress() * 100)}%", end="\r")

    video_id  = response["id"]
    video_url = f"https://youtube.com/shorts/{video_id}"
    print(f"\n  [✓] Uploaded to YouTube: {video_url}")
    return video_id


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--auth", action="store_true",
                        help="Run OAuth flow to authorize YouTube access (local only)")
    args = parser.parse_args()

    if args.auth:
        print("Opening browser for YouTube authorization...")
        get_credentials()
        print("\nDone! Now run:")
        print('  python -c "import base64; print(base64.b64encode(open(\'token.pickle\',\'rb\').read()).decode())"')
        print("Copy that output → add as GitHub Secret: YOUTUBE_TOKEN_PICKLE")
    else:
        print("Usage: python platform/youtube_upload.py --auth")
